#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#ifndef BAREMETAL
#include <sys/mman.h>
#endif
#include "include/gemmini.h"
#include "include/gemmini_nn.h"

#include "resnet50_params.h"
// #include "resnet50_params_1batch.h"
#include "images.h"

int main (int argc, char * argv[]) {

    printf("Conv_1: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_1_params.I, conv_1_params.J, conv_1_params.K, conv_1_params.kernel_size, conv_1_params.in_channels, conv_1_params.out_channels, conv_1_params.out_row_dim, conv_1_params.out_col_dim);
printf("Conv_2: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_2_params.I, conv_2_params.J, conv_2_params.K, conv_2_params.kernel_size, conv_2_params.in_channels, conv_2_params.out_channels, conv_2_params.out_row_dim, conv_2_params.out_col_dim);
printf("Conv_3: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_3_params.I, conv_3_params.J, conv_3_params.K, conv_3_params.kernel_size, conv_3_params.in_channels, conv_3_params.out_channels, conv_3_params.out_row_dim, conv_3_params.out_col_dim);
printf("Conv_4: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_4_params.I, conv_4_params.J, conv_4_params.K, conv_4_params.kernel_size, conv_4_params.in_channels, conv_4_params.out_channels, conv_4_params.out_row_dim, conv_4_params.out_col_dim);
printf("Conv_5: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_5_params.I, conv_5_params.J, conv_5_params.K, conv_5_params.kernel_size, conv_5_params.in_channels, conv_5_params.out_channels, conv_5_params.out_row_dim, conv_5_params.out_col_dim);
printf("Conv_6: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_6_params.I, conv_6_params.J, conv_6_params.K, conv_6_params.kernel_size, conv_6_params.in_channels, conv_6_params.out_channels, conv_6_params.out_row_dim, conv_6_params.out_col_dim);
printf("Conv_7: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_7_params.I, conv_7_params.J, conv_7_params.K, conv_7_params.kernel_size, conv_7_params.in_channels, conv_7_params.out_channels, conv_7_params.out_row_dim, conv_7_params.out_col_dim);
printf("Conv_8: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_8_params.I, conv_8_params.J, conv_8_params.K, conv_8_params.kernel_size, conv_8_params.in_channels, conv_8_params.out_channels, conv_8_params.out_row_dim, conv_8_params.out_col_dim);
printf("Conv_9: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_9_params.I, conv_9_params.J, conv_9_params.K, conv_9_params.kernel_size, conv_9_params.in_channels, conv_9_params.out_channels, conv_9_params.out_row_dim, conv_9_params.out_col_dim);
printf("Conv_10: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_10_params.I, conv_10_params.J, conv_10_params.K, conv_10_params.kernel_size, conv_10_params.in_channels, conv_10_params.out_channels, conv_10_params.out_row_dim, conv_10_params.out_col_dim);
printf("Conv_11: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_11_params.I, conv_11_params.J, conv_11_params.K, conv_11_params.kernel_size, conv_11_params.in_channels, conv_11_params.out_channels, conv_11_params.out_row_dim, conv_11_params.out_col_dim);
printf("Conv_12: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_12_params.I, conv_12_params.J, conv_12_params.K, conv_12_params.kernel_size, conv_12_params.in_channels, conv_12_params.out_channels, conv_12_params.out_row_dim, conv_12_params.out_col_dim);
printf("Conv_13: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_13_params.I, conv_13_params.J, conv_13_params.K, conv_13_params.kernel_size, conv_13_params.in_channels, conv_13_params.out_channels, conv_13_params.out_row_dim, conv_13_params.out_col_dim);
printf("Conv_14: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_14_params.I, conv_14_params.J, conv_14_params.K, conv_14_params.kernel_size, conv_14_params.in_channels, conv_14_params.out_channels, conv_14_params.out_row_dim, conv_14_params.out_col_dim);
printf("Conv_15: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_15_params.I, conv_15_params.J, conv_15_params.K, conv_15_params.kernel_size, conv_15_params.in_channels, conv_15_params.out_channels, conv_15_params.out_row_dim, conv_15_params.out_col_dim);
printf("Conv_16: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_16_params.I, conv_16_params.J, conv_16_params.K, conv_16_params.kernel_size, conv_16_params.in_channels, conv_16_params.out_channels, conv_16_params.out_row_dim, conv_16_params.out_col_dim);
printf("Conv_17: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_17_params.I, conv_17_params.J, conv_17_params.K, conv_17_params.kernel_size, conv_17_params.in_channels, conv_17_params.out_channels, conv_17_params.out_row_dim, conv_17_params.out_col_dim);
printf("Conv_18: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_18_params.I, conv_18_params.J, conv_18_params.K, conv_18_params.kernel_size, conv_18_params.in_channels, conv_18_params.out_channels, conv_18_params.out_row_dim, conv_18_params.out_col_dim);
printf("Conv_19: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_19_params.I, conv_19_params.J, conv_19_params.K, conv_19_params.kernel_size, conv_19_params.in_channels, conv_19_params.out_channels, conv_19_params.out_row_dim, conv_19_params.out_col_dim);
printf("Conv_20: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_20_params.I, conv_20_params.J, conv_20_params.K, conv_20_params.kernel_size, conv_20_params.in_channels, conv_20_params.out_channels, conv_20_params.out_row_dim, conv_20_params.out_col_dim);
printf("Conv_21: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_21_params.I, conv_21_params.J, conv_21_params.K, conv_21_params.kernel_size, conv_21_params.in_channels, conv_21_params.out_channels, conv_21_params.out_row_dim, conv_21_params.out_col_dim);
printf("Conv_22: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_22_params.I, conv_22_params.J, conv_22_params.K, conv_22_params.kernel_size, conv_22_params.in_channels, conv_22_params.out_channels, conv_22_params.out_row_dim, conv_22_params.out_col_dim);
printf("Conv_23: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_23_params.I, conv_23_params.J, conv_23_params.K, conv_23_params.kernel_size, conv_23_params.in_channels, conv_23_params.out_channels, conv_23_params.out_row_dim, conv_23_params.out_col_dim);
printf("Conv_24: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_24_params.I, conv_24_params.J, conv_24_params.K, conv_24_params.kernel_size, conv_24_params.in_channels, conv_24_params.out_channels, conv_24_params.out_row_dim, conv_24_params.out_col_dim);
printf("Conv_25: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_25_params.I, conv_25_params.J, conv_25_params.K, conv_25_params.kernel_size, conv_25_params.in_channels, conv_25_params.out_channels, conv_25_params.out_row_dim, conv_25_params.out_col_dim);
printf("Conv_26: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_26_params.I, conv_26_params.J, conv_26_params.K, conv_26_params.kernel_size, conv_26_params.in_channels, conv_26_params.out_channels, conv_26_params.out_row_dim, conv_26_params.out_col_dim);
printf("Conv_27: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_27_params.I, conv_27_params.J, conv_27_params.K, conv_27_params.kernel_size, conv_27_params.in_channels, conv_27_params.out_channels, conv_27_params.out_row_dim, conv_27_params.out_col_dim);
printf("Conv_28: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_28_params.I, conv_28_params.J, conv_28_params.K, conv_28_params.kernel_size, conv_28_params.in_channels, conv_28_params.out_channels, conv_28_params.out_row_dim, conv_28_params.out_col_dim);
printf("Conv_29: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_29_params.I, conv_29_params.J, conv_29_params.K, conv_29_params.kernel_size, conv_29_params.in_channels, conv_29_params.out_channels, conv_29_params.out_row_dim, conv_29_params.out_col_dim);
printf("Conv_30: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_30_params.I, conv_30_params.J, conv_30_params.K, conv_30_params.kernel_size, conv_30_params.in_channels, conv_30_params.out_channels, conv_30_params.out_row_dim, conv_30_params.out_col_dim);
printf("Conv_31: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_31_params.I, conv_31_params.J, conv_31_params.K, conv_31_params.kernel_size, conv_31_params.in_channels, conv_31_params.out_channels, conv_31_params.out_row_dim, conv_31_params.out_col_dim);
printf("Conv_32: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_32_params.I, conv_32_params.J, conv_32_params.K, conv_32_params.kernel_size, conv_32_params.in_channels, conv_32_params.out_channels, conv_32_params.out_row_dim, conv_32_params.out_col_dim);
printf("Conv_33: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_33_params.I, conv_33_params.J, conv_33_params.K, conv_33_params.kernel_size, conv_33_params.in_channels, conv_33_params.out_channels, conv_33_params.out_row_dim, conv_33_params.out_col_dim);
printf("Conv_34: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_34_params.I, conv_34_params.J, conv_34_params.K, conv_34_params.kernel_size, conv_34_params.in_channels, conv_34_params.out_channels, conv_34_params.out_row_dim, conv_34_params.out_col_dim);
printf("Conv_35: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_35_params.I, conv_35_params.J, conv_35_params.K, conv_35_params.kernel_size, conv_35_params.in_channels, conv_35_params.out_channels, conv_35_params.out_row_dim, conv_35_params.out_col_dim);
printf("Conv_36: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_36_params.I, conv_36_params.J, conv_36_params.K, conv_36_params.kernel_size, conv_36_params.in_channels, conv_36_params.out_channels, conv_36_params.out_row_dim, conv_36_params.out_col_dim);
printf("Conv_37: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_37_params.I, conv_37_params.J, conv_37_params.K, conv_37_params.kernel_size, conv_37_params.in_channels, conv_37_params.out_channels, conv_37_params.out_row_dim, conv_37_params.out_col_dim);
printf("Conv_38: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_38_params.I, conv_38_params.J, conv_38_params.K, conv_38_params.kernel_size, conv_38_params.in_channels, conv_38_params.out_channels, conv_38_params.out_row_dim, conv_38_params.out_col_dim);
printf("Conv_39: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_39_params.I, conv_39_params.J, conv_39_params.K, conv_39_params.kernel_size, conv_39_params.in_channels, conv_39_params.out_channels, conv_39_params.out_row_dim, conv_39_params.out_col_dim);
printf("Conv_40: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_40_params.I, conv_40_params.J, conv_40_params.K, conv_40_params.kernel_size, conv_40_params.in_channels, conv_40_params.out_channels, conv_40_params.out_row_dim, conv_40_params.out_col_dim);
printf("Conv_41: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_41_params.I, conv_41_params.J, conv_41_params.K, conv_41_params.kernel_size, conv_41_params.in_channels, conv_41_params.out_channels, conv_41_params.out_row_dim, conv_41_params.out_col_dim);
printf("Conv_42: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_42_params.I, conv_42_params.J, conv_42_params.K, conv_42_params.kernel_size, conv_42_params.in_channels, conv_42_params.out_channels, conv_42_params.out_row_dim, conv_42_params.out_col_dim);
printf("Conv_43: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_43_params.I, conv_43_params.J, conv_43_params.K, conv_43_params.kernel_size, conv_43_params.in_channels, conv_43_params.out_channels, conv_43_params.out_row_dim, conv_43_params.out_col_dim);
printf("Conv_44: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_44_params.I, conv_44_params.J, conv_44_params.K, conv_44_params.kernel_size, conv_44_params.in_channels, conv_44_params.out_channels, conv_44_params.out_row_dim, conv_44_params.out_col_dim);
printf("Conv_45: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_45_params.I, conv_45_params.J, conv_45_params.K, conv_45_params.kernel_size, conv_45_params.in_channels, conv_45_params.out_channels, conv_45_params.out_row_dim, conv_45_params.out_col_dim);
printf("Conv_46: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_46_params.I, conv_46_params.J, conv_46_params.K, conv_46_params.kernel_size, conv_46_params.in_channels, conv_46_params.out_channels, conv_46_params.out_row_dim, conv_46_params.out_col_dim);
printf("Conv_47: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_47_params.I, conv_47_params.J, conv_47_params.K, conv_47_params.kernel_size, conv_47_params.in_channels, conv_47_params.out_channels, conv_47_params.out_row_dim, conv_47_params.out_col_dim);
printf("Conv_48: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_48_params.I, conv_48_params.J, conv_48_params.K, conv_48_params.kernel_size, conv_48_params.in_channels, conv_48_params.out_channels, conv_48_params.out_row_dim, conv_48_params.out_col_dim);
printf("Conv_49: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_49_params.I, conv_49_params.J, conv_49_params.K, conv_49_params.kernel_size, conv_49_params.in_channels, conv_49_params.out_channels, conv_49_params.out_row_dim, conv_49_params.out_col_dim);
printf("Conv_50: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_50_params.I, conv_50_params.J, conv_50_params.K, conv_50_params.kernel_size, conv_50_params.in_channels, conv_50_params.out_channels, conv_50_params.out_row_dim, conv_50_params.out_col_dim);
printf("Conv_51: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_51_params.I, conv_51_params.J, conv_51_params.K, conv_51_params.kernel_size, conv_51_params.in_channels, conv_51_params.out_channels, conv_51_params.out_row_dim, conv_51_params.out_col_dim);
printf("Conv_52: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_52_params.I, conv_52_params.J, conv_52_params.K, conv_52_params.kernel_size, conv_52_params.in_channels, conv_52_params.out_channels, conv_52_params.out_row_dim, conv_52_params.out_col_dim);
printf("Conv_53: I: %d, J: %d, K: %d, kernel_size: %d, in_channels: %d, out_channels: %d, out_row_dim: %d, out_col_dim: %d\n", conv_53_params.I, conv_53_params.J, conv_53_params.K, conv_53_params.kernel_size, conv_53_params.in_channels, conv_53_params.out_channels, conv_53_params.out_row_dim, conv_53_params.out_col_dim);
	printf("Fc_54: I: %d, J: %d, K: %d\n", fc_54_params.I, fc_54_params.J, fc_54_params.K);

    return 0;
}